// <auto-generated />
namespace MVC5MovieStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class new5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new5));
        
        string IMigrationMetadata.Id
        {
            get { return "201601211600100_new5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
